<?php 
require_once('inc/init.inc.php');

require_once('inc/haut.inc.php');

echo'<h1> Mentions légales</h1>';
echo'<h2> Ce site est fictif</h2>';
echo'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras blandit vehicula scelerisque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed commodo augue diam, et tempor nunc posuere ac. Mauris sed pulvinar metus. Donec et ligula bibendum, dapibus arcu eget, ultricies turpis. Quisque congue quam id leo facilisis, quis feugiat magna porttitor. Nam sit amet tellus ut turpis elementum ornare. Ut imperdiet mauris lectus, eget pharetra diam varius id. Sed a laoreet ante, sed sagittis nulla. Nullam dictum leo erat, non finibus justo elementum id. Suspendisse blandit vel velit eu fermentum. Morbi euismod mauris ligula, varius bibendum elit accumsan a. Phasellus mollis ac purus id tincidunt. Praesent malesuada hendrerit turpis, in sodales lacus varius non.

Donec nec erat elementum dolor efficitur pellentesque volutpat gravida metus. Phasellus id purus sit amet elit euismod auctor. Praesent mattis magna dapibus ipsum egestas, non molestie nulla sollicitudin. In quis ullamcorper nulla. Pellentesque congue luctus eros a tincidunt. Cras id diam ac dui aliquam tincidunt quis eu leo. Aenean aliquet fermentum nisl quis tempus. Proin nec diam nec metus vulputate sollicitudin. Nunc scelerisque massa ut nisl feugiat malesuada. Phasellus blandit purus et tristique vehicula. Aenean tortor arcu, tincidunt nec imperdiet eget, sodales quis turpis. Cras convallis in nibh a egestas. Sed vestibulum turpis a risus bibendum laoreet. Curabitur eget nulla justo. Phasellus nec augue lacus. Donec faucibus ante sed elit bibendum bibendum.

Pellentesque volutpat, turpis a luctus hendrerit, dolor risus luctus urna, ac pharetra lacus arcu eget massa. Vestibulum rhoncus aliquam sagittis. Ut tincidunt nulla eget tellus suscipit, in tincidunt justo luctus. Donec eros risus, pretium sit amet placerat et, condimentum interdum diam. Sed faucibus ultrices justo, ac condimentum velit condimentum at. Aenean vitae arcu dictum, malesuada magna in, ultricies nisl. Morbi ornare sem tristique eros scelerisque, vestibulum lacinia purus bibendum. Mauris fringilla neque non diam bibendum, nec faucibus ante suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras blandit vehicula scelerisque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed commodo augue diam, et tempor nunc posuere ac. Mauris sed pulvinar metus. Donec et ligula bibendum, dapibus arcu eget, ultricies turpis. Quisque congue quam id leo facilisis, quis feugiat magna porttitor. Nam sit amet tellus ut turpis elementum ornare. Ut imperdiet mauris lectus, eget pharetra diam varius id. Sed a laoreet ante, sed sagittis nulla. Nullam dictum leo erat, non finibus justo elementum id. Suspendisse blandit vel velit eu fermentum. Morbi euismod mauris ligula, varius bibendum elit accumsan a. Phasellus mollis ac purus id tincidunt. Praesent malesuada hendrerit turpis, in sodales lacus varius non.

Donec nec erat elementum dolor efficitur pellentesque volutpat gravida metus. Phasellus id purus sit amet elit euismod auctor. Praesent mattis magna dapibus ipsum egestas, non molestie nulla sollicitudin. In quis ullamcorper nulla. Pellentesque congue luctus eros a tincidunt. Cras id diam ac dui aliquam tincidunt quis eu leo. Aenean aliquet fermentum nisl quis tempus. Proin nec diam nec metus vulputate sollicitudin. Nunc scelerisque massa ut nisl feugiat malesuada. Phasellus blandit purus et tristique vehicula. Aenean tortor arcu, tincidunt nec imperdiet eget, sodales quis turpis. Cras convallis in nibh a egestas. Sed vestibulum turpis a risus bibendum laoreet. Curabitur eget nulla justo. Phasellus nec augue lacus. Donec faucibus ante sed elit bibendum bibendum.

Pellentesque volutpat, turpis a luctus hendrerit, dolor risus luctus urna, ac pharetra lacus arcu eget massa. Vestibulum rhoncus aliquam sagittis. Ut tincidunt nulla eget tellus suscipit, in tincidunt justo luctus. Donec eros risus, pretium sit amet placerat et, condimentum interdum diam. Sed faucibus ultrices justo, ac condimentum velit condimentum at. Aenean vitae arcu dictum, malesuada magna in, ultricies nisl. Morbi ornare sem tristique eros scelerisque, vestibulum lacinia purus bibendum. Mauris fringilla neque non diam bibendum, nec faucibus ante suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.';

require_once('inc/bas.inc.php');
